/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package productos;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author juanalvarenga
 */
public class ProductoDialog extends javax.swing.JDialog {

    /**
     * Creates new form ProductoDialog
     */
    public ProductoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public String getProducto() {
        //return txtProducto.getText();
        return String.valueOf(comboProducto.getSelectedItem());
    }

    public int getCantidad() {
        //return Integer.parseInt(txtCantidad.getText());
        return Integer.parseInt(spinCantidad.getValue().toString());
    }

    public double getPrecio() {
        //return Double.parseDouble(txtPrecio.getText());
        return Double.parseDouble(spinPrecio.getValue().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        btnGurdar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        comboProducto = new javax.swing.JComboBox<>();
        spinCantidad = new javax.swing.JSpinner();
        spinPrecio = new javax.swing.JSpinner();
        lblProducto1 = new javax.swing.JLabel();
        lblProducto2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Admin productos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Cantidad:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Precio:");

        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });

        btnGurdar.setText("Guardar");
        btnGurdar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGurdarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        comboProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coca-Cola 500 ML", "Pepsi 500 ML", "Monster 800 ML", "RedBull 450 ML", "Agua Mineral 400 ML", "Te Lipton 800 ML" }));
        comboProducto.setName(""); // NOI18N
        comboProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductoActionPerformed(evt);
            }
        });

        spinCantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        spinPrecio.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 999.0d, 1.0d));

        lblProducto1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblProducto1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProducto1.setText("Producto:");

        lblProducto2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblProducto2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProducto2.setText("Producto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnGurdar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblProducto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblProducto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(spinCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboProducto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(spinPrecio))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProducto1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProducto2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGurdar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        //TODO: notificar al padre que se canceló la operación
        //cerrar la ventana
        
        this.setRootPane(null); // estoy destruyendo los elementos en la UI
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGurdarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGurdarActionPerformed

        //TODO: 1. validar los campos para que acepten los valores correctos
        //String producto = txtProducto.getText();
        String producto = String.valueOf(comboProducto.getSelectedItem());
        //int cantidad;
        int cantidad;
        double precio;

        try {
            //cantidad = Integer.parseInt(txtCantidad.getText());
            cantidad = Integer.parseInt(spinCantidad.getValue().toString());
            //precio = Double.parseDouble(txtPrecio.getText());
            precio = Double.parseDouble(spinPrecio.getValue().toString());
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "Verifique los valores ingresados: " + e.getMessage(),
                    "Datos numericos incorrectos",
                    JOptionPane.WARNING_MESSAGE
            );

            return;

        }

        if (producto.isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "El nombre de producto no puede ser vacio",
                    "Producto incorrecto",
                    JOptionPane.WARNING_MESSAGE
            );

            return;

        }

        if (cantidad <= 0) {

            JOptionPane.showMessageDialog(this,
                    "La cantidad debe ser mayor a cero",
                    "Cantidad incorrecta",
                    JOptionPane.WARNING_MESSAGE
            );

            return;

        }

        if (precio <= 0) {

            JOptionPane.showMessageDialog(this,
                    "El preecio debe ser mayor a cero",
                    "Precio incorrecto",
                    JOptionPane.WARNING_MESSAGE
            );

            return;

        }

        //2. confirmar que queremos guardar
        int respuesta = JOptionPane.showConfirmDialog(this, "Quieres agregar este producto?");

                //guardar en la tabla
        if (respuesta == 0) {
            this.setVisible(false);
        }//3. notifcar al padre que todo está en orden y que proceda a 



    }//GEN-LAST:event_btnGurdarActionPerformed

    private void comboProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductoActionPerformed
        // TODO add your handling code here:
        /*String valor = String.valueOf(comboProducto.getSelectedItem());
        int index = comboProducto.getSelectedIndex();

        JOptionPane.showMessageDialog(null, "valor: " + valor + ", indice: " + index);*/
    }//GEN-LAST:event_comboProductoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();

        modelo.addElement(null);
        modelo.addElement("Coca-Cola 500 ML");
        modelo.addElement("Pepsi 500 ML");
        modelo.addElement("Monster 800 ML");
        modelo.addElement("RedBull 450 ML");
        modelo.addElement("Agua Mineral 400 ML");
        modelo.addElement("Te Lipton 800 ML");

        comboProducto.setModel(modelo);
    }//GEN-LAST:event_formWindowOpened

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProductoDialog dialog = new ProductoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGurdar;
    public javax.swing.JComboBox<String> comboProducto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel lblProducto1;
    public javax.swing.JLabel lblProducto2;
    public javax.swing.JSpinner spinCantidad;
    public javax.swing.JSpinner spinPrecio;
    public javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
